### ISSUE TITLE
Support work item templates

### ISSUE THREAD

**Issue by Aidurber** [boylec/sentry-vsts#6]
Hi, 
I've just created an issue on the Sentry repo but I think it would be better asking it here. 
https://github.com/getsentry/sentry/issues/6360

Would it be possible to support Work Item Templates? So we could create a template and pass its ID and store it against the integration settings?

So when we share an issue the template ID is populated in the query string. Docs for it here: https://docs.microsoft.com/en-us/vsts/work/backlogs/work-item-template?tabs=browser

Do I even raise this issue here or in: https://github.com/getsentry/sentry-plugins/

Getting a tad confused. I'd be happy to take a look and see what I can do but I'm no Python developer :smile:

**Comment by boylec** [comment]
Post it in the main sentry plug-ins repo - the sentry team decided to pull this plugin into there rather than have it hosted in a separate git repo.

Thanks!

 Casey Boyle

On Oct 18, 2017, at 1:21 PM, Andrew Durber <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I've just created an issue on the Sentry repo but I think it would be better asking it here.
getsentry/sentry#6360<https://github.com/getsentry/sentry/issues/6360>

Would it be possible to support Work Item Templates? So we could create a template and pass its ID and store it against the integration settings?

So when we share an issue the template ID is populated in the query string. Docs for it here: https://docs.microsoft.com/en-us/vsts/work/backlogs/work-item-template?tabs=browser

Do I even raise this issue here or in: https://github.com/getsentry/sentry-plugins/

Getting a tad confused. I'd be happy to take a look and see what I can do but I'm no Python developer 😄

**Comment by Aidurber** [comment]
Awesome will do, thank you Casey.
